### ISSUE TITLE
# Error: 'list' object has no attribute 'translateX'

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#182]
_From [martinmr...@gmail.com](https://code.google.com/u/104964565455221587725/) on January 15, 2010 05:13:26_

What Version of Maya are you using? On what operating system? (Please be as specific as possible and include service packs, 64bit vs 32bit, etc) Maya 2009 64bit WindowsXP Pro 64bit What Version of PyMEL are you using? pymel-1.0.0rc1 What is the expected output? What do you see instead? If possible, provide a few lines of code to reproduce the problem. Expected
Attribute(u'pPlane1.translateX')

What I do see instead
\# Error: 'list' object has no attribute 'translateX' Is there a maya.cmds or maya.OpenMaya equivalent to the pymel function in question? ( For example, pymel.listRelatives --> maya.cmds.listRelatives )
If so, does it exhibit the same problem? not sure. Please provide any additional information below. I just installed this version today, before this version I didn't have any
problems.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=147_

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on January 15, 2010 08:26:47_

hi. you never actually posted any context for your problem.  please reread what you 
posted and add some context or code to this problem.

**Comment by elrond79** [comment]
_From [martinmr...@gmail.com](https://code.google.com/u/104964565455221587725/) on January 15, 2010 11:56:50_

Hi there,

I was just simply following one of the examples from the docs. I created a polyplane
and when I try to access the attribute (translateX) I got some errors shown below.
Here is what I have typed in the script editor

from pymel import *
import pymel as pm

plane1 = pm.polyPlane()
plane1

plane1.translateX

After selecting "plane1.translateX" and pressing Crtl +Enter
Result:

\# Error: 'module' object has no attribute 'polyPlane'
\# Traceback (most recent call last):
\#   File "<maya console>", line 5, in \<module>
\# AttributeError: 'module' object has no attribute 'polyPlane' # 

This is all I have done with the plane and that's the error message I got. 

Let me know if you need more info.

Martin

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on January 15, 2010 23:47:16_

from now on when you post an issue please include the description of what you were 
doing being as detailed as possible.  you still have not told me WHICH example you 
were running.  also, please first post this to the user group.  this section of the site is 
for suspected bugs.  there are many people on the python_inside_maya user group 
who can help you with these simpler problems.

the example that you are running does not appear anywhere in the pymel 1.0 docs, 
as far as i can tell: http://www.luma-pictures.com/tools/pymel/docs/1.0/index.html are you using the 1.0 docs or the 0.9 docs?

**Status:** Invalid

**Comment by elrond79** [comment]
_From [martinmr...@gmail.com](https://code.google.com/u/104964565455221587725/) on January 16, 2010 00:20:09_

Hello Chad, 

I am so sorry that I have been posting stupid things. I don't think I ever made so many mistakes in a row. I 
have been working pretty late and I have been making a lot of mistakes. 

The docs that I was looking at is version 0.9 http://pymel.googlecode.com/svn/docs/tutorial.html And the example I was running was the attributes example. 

I am working with Pymel version  1.0 and that explain my errors. Once again I am so sorry that I made this 
mistakes, from now on I'll be more careful about these things.

Martin
